name: quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

  cupertino_icons: ^1.0.8
  #comparing dart object
  equatable: ^2.0.5
  #makes api request:
  retrofit: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.12
  build: ^2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/subjects_bg.svg
  #   - images/a_dot_ham.jpeg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
